apiVersion: v1
kind: Pod
metadata:
  name: label-demo
  labels:
   course: DevOps
   Trainer: "sivakumarreddy"
spec:
  containers:
  - name: hello-pod
    image: nginx
    ports:
    - containerPort: 80